Fix broken tests due to TypeError
Prevents rstrip() from generating the following error:

```
ERROR: test_should_return_name_when_addt_record_is_missing (tests.WhenLookingUpRecords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryans/git/github.com/srvlookup/tests.py", line 91, in test_should_return_name_when_addt_record_is_missing
    self.assertEqual(srvlookup.lookup('foo', 'bar', 'baz'),
  File "/Users/ryans/git/github.com/srvlookup/srvlookup.py", line 52, in lookup
    results = _build_result_set(answer)
  File "/Users/ryans/git/github.com/srvlookup/srvlookup.py", line 125, in _build_result_set
    target.rstrip('.'),
TypeError: a bytes-like object is required, not 'str'
```

Tested with Python2.7 and Python3.5